# Twitter上のユーザの気になるワードヒット記録
CREATE TABLE TWITTER_USER_CHECKED(
	# Twitter上のユーザID
	TWITTER_USER_ID BIGINT UNSIGNED NOT NULL,
	# いつ検索したか
	SEARCHED_AT DATE NOT NULL,
	# そのツイートのID
	TWEET_ID BIGINT UNSIGNED NOT NULL,
	
	# ユーザIDは外部キー
	FOREIGN KEY( TWITTER_USER_ID )
	REFERENCES TWITTER_USER( TWITTER_USER_ID ),

	# ツイートIDも外部キー
	FOREIGN KEY( TWEET_ID )
	REFERENCES TWEET( TWEET_ID )

	# ユーザIDとツイートIDの組み合わせは
	# 一意
	UNIQUE( TWITTER_USER_ID, TWEET_ID )
);
